apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/seneca-bookstore"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-data-pvc
  namespace: seneca-bookstore
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
