apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: seneca-bookstore
  labels:
    app: catalog-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
        component: api
    spec:
      serviceAccountName: catalog-service-sa
      containers:
      - name: catalog-service
        image: localhost:5000/catalog-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "sqlite:////tmp/catalog.db"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: USER_SERVICE_URL
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: CORS_ORIGINS
        - name: ADMIN_EMAILS
          value: "admin@seneca.ca,admin@example.com"
        volumeMounts:
        - name: data-storage
          mountPath: /data
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: bookstore-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: seneca-bookstore
  labels:
    app: catalog-service
    component: backend
spec:
  selector:
    app: catalog-service
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
