apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: seneca-bookstore
  labels:
    app: frontend-service
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
        component: frontend
    spec:
      serviceAccountName: frontend-service-sa
      containers:
      - name: frontend-service
        image: localhost:5000/frontend-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_USER_SERVICE_URL
          value: "http://senecabooks.local/api/user"
        - name: REACT_APP_CATALOG_SERVICE_URL
          value: "http://senecabooks.local/api/catalog"
        - name: REACT_APP_ORDER_SERVICE_URL
          value: "http://senecabooks.local/api/order"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: seneca-bookstore
  labels:
    app: frontend-service
    component: frontend
spec:
  selector:
    app: frontend-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
