apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: seneca-bookstore
  labels:
    app: user-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: api
    spec:
      serviceAccountName: user-service-sa
      containers:
      - name: user-service
        image: localhost:5000/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          value: "sqlite:////tmp/users.db"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: CORS_ORIGINS
        volumeMounts:
        - name: data-storage
          mountPath: /data
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: bookstore-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: seneca-bookstore
  labels:
    app: user-service
    component: backend
spec:
  selector:
    app: user-service
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
